FROM node:22-slim

# تثبيت Python3 و pip
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

# تثبيت مكتبات Python الخفيفة
RUN pip3 install \
    openpyxl \
    pandas \
    python-docx \
    PyPDF2 \
    pillow \
    --break-system-packages

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 8080
CMD ["npm", "start"]